### PR TITLE
A Major Refactor and Optimization

### PR DESCRIPTION
**Pull request by qe201020335**
(We can communicate in Chinese if you prefer)

I had a fork a while back building the mod for the intermediate test versions of Aki 3.8.0 and [SIT](https://github.com/stayintarkov/StayInTarkov.Client). 

I have not looked at the code until now because it is somehow causing the game to take upwards of 30 minutes on "loading loot". Upon checking the code I realized that the project structure at the current state is quite a mess. I am going to refactor and possibly rewrite a major part of the mod in my fork. Considering you are still maintaining this mods and adding new features, I think you may also want to have a fresh project structure that is easy to maintain in the future. 

If you want, I will update my fork with your changes, then do the refactor part by part and pr them. If you think otherwise, please close this pr.

A rough idea on the refactor:
- [x] Update `.gitignore` and remove extra files in the repo
- [x] Make separate directories for the mod and unity project
- [x] Move the main classes to their dedicated files
- [x] Embed the radar asset bundle into the assembly
- [x] Decouple asset bundle loading from the MonoBehavior
- [x] Instantiate Rader and related scripts only when necessary using hooks instead of checking `MapLoaded` everything single frame

Things I can do later (probably another pr) :
- Properly cache things and DON'T `GetComponent` every single frame. (THIS IS SLOW)
- Move most of the query logic from the main thread to worker threads
...

Will add more when I get to them

### CODE REVIEW

**Comment by qe201020335** [comment]
A rough idea on the refactor:

- [ ] Make separate directories for the mod and unity project
- [ ] Move the main classes to their dedicated files
- [ ] Decouple asset bundle loading from the MonoBehavior
- [ ] Instantiate Rader and related scripts only when necessary using hooks instead of checking `MapLoaded` everything single frame
...

Will add more when I get to them

**Comment by yhl452493373** [comment]
SIT中，开启雷达的情况下进图，除了工厂，其他图都有加载战利品问题。目前我发现的解决办法是卡住的时候按F10关闭雷达，进游戏后再打开。这个代码不好改的情况，可能需要配合SIT模块，在游戏开始前关闭雷达，开始后启用。

**Comment by qe201020335** [comment]
@yhl452493373 这个mod里的MonoBehavior在每一帧都被调用的地方做了不该做的事，非常非常慢，而且不论游戏是否已加载都会尝试调用雷达的脚本

我要把整个雷达Object的实例化限制在游戏加载的事件上，符合Unity本身的对象生命周期。这样只有游戏加载好了才会生成雷达，从根本上解决加载变慢问题

我就是因为在SIT上出现了问题才看的代码，一看不得了，全是问题

**Comment by yhl452493373** [comment]
@qe201020335 不懂unity，不过这个确实和其他的不太一样，进藏身处都会出雷达。等大佬优化。(#^.^#)

**Comment by qe201020335** [comment]
@yhl452493373 e0173031d945eb34aaa3b6b9379cc280f1b2dba5 已经不卡加载了，你可以试试
[radar-0.14.1.2.29197-sit.zip](https://github.com/Leonana69/Tyrian-Radar-Standalone/files/14741348/radar-0.14.1.2.29197-sit.zip)
别开探测物资，巨慢，之后我会优化这部分

**Comment by yhl452493373** [comment]
@qe201020335 👌🏻

**Comment by qe201020335** [comment]
This is already a good optimization/refactor and is mergeable. I can open another pr for other optimizations

**Comment by qe201020335** [comment]
> @qe201020335 👌🏻

@yhl452493373 加Discord吗，搜qe201020335
用GitHub交流效率有点低

**Comment by Leonana69** [comment]
This patch is generally good. The radar scan animation won't start after enabling/disabling, please solve that issue.
Then after I test with the loot detection, I'll merge this patch.

**Comment by qe201020335** [comment]
@Leonana69 Thanks for the reply! I will take a look into this issue.

**Comment by qe201020335** [comment]
There was an issue with loot detection when I was testing, though. It relies on the cached trader and flea offers to determine the item prices. If you start a raid without ever opening the trader and flea screen, all the items will have a price of 0.

**Comment by qe201020335** [comment]
@Leonana69 I have fixed the issue.

Keep in mind that you don't need to copy the radar asset bundle file into the plugins folder anymore. It is an embedded resource now and will be loaded directly from memory.

**Pull request merged**
